### ISSUE TITLE
Multiprocessing issue? Advice on running multiple trains at the same time

### ISSUE THREAD

**Issue by xwong22** [Kami-code/dexart-release#15]
Hi, I have been trying to run a few training at the same time using the example code given in the README.md. I noticed that some of the runs take a very long time, almost looking like it is stuck. Therefore, I went to check the fps in the tensorboard log.

![d28efa13351e7fdae1a120c0ade506b](https://github.com/Kami-code/dexart-release/assets/77428413/52e5e363-0891-4b13-9e44-2a85facbc6f4)

I started one training at 17:37 and then another at 17:42. I noticed that there is a drop in fps (blue line) at 17:42, exactly when the second train is started. It seems like there is an issue with multiprocessing. When I run more trains at the same time, the drop in fps is even sharper.

I have checked my cpu and gpu resources, they aren't full. top command also shows that there are unused cpu capacity, even when some of the trains are stuck.

May I know is it possible to run multiple trains at the same time? If yes, can you please advise on how to estimate the maximum number of trains I can run?

Here are some details of the server I used:
GPU: NVIDIA GeForce RTX 3090 * 4
CPU: 60 cores
Memory: 320 GB

**Comment by Kami-code** [comment]
Hi, @xwong22 . Thanks for using our benchmark. I think your problem is a bit tricky, because each of our experiments is run solely on a machine every time(one job for each experiment on k8s). I can not ensure our code supports running multiple trains at the same time on one machine, but I can give you some debug processes. First, each epoch's time can be divided into collect_rollouts(running simulation) and training models(use trajectories to calculate loss and backpropagation). You can try to print the time of those two parts to see what causes the problem. As you mentioned, maybe the problem lies in the multi-process of the SAPIEN simulator. And you may dig into the implementation details to debug it. Also, I think the [SAPIEN repo](https://github.com/haosulab/SAPIEN) is also actively maintained. You can submit a issue for help if you do think there is some problem related to SAPIEN.

Good luck!

**Comment by xwong22** [comment]
I see, thank you so much for the prompt reply! May I know what are the specifications of your machine and how long did it take to train the different tasks to obtain the results demonstrated in Figure 6 in your paper?

**Comment by Kami-code** [comment]
The details of our machine can be found [here](https://github.com/Kami-code/dexart-release/issues/1#issuecomment-1611352302). The training details can be found [here](https://github.com/Kami-code/dexart-release/issues/1#issuecomment-1557198625). The training  of laptop may take more time than 15h for some reason.

**Comment by xwong22** [comment]
Alright, noted. Thank you so much for your help!
